version: '3.7'

services:
  speech-api:
    build:
      context: ./realtime-transcription-browser-js-example
      dockerfile: Dockerfile
    ports:
      - '8000:8000'

  action-service:
    container_name: action-server
    build:
      context: ./rasa
      dockerfile: Dockerfile
    volumes:
     - ./rasa/actions:/app/actions

  rasa:
    image: rasa/rasa:3.0.6-full
    volumes:
      - './rasa:/app'
      - ./rasa/models:/app/models
    ports:
      - '5005:5005'
    command: run --enable-api --cors "*"

  museum:
    container_name: museum-prod
    build:
      context: ./museum-app
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'